<?xml version="1.0"?>
<package format="2">
  <name>qrcode_reader</name>
  <version>0.0.1</version>
  <description>The qrcode_reader package</description>

  <maintainer email="wang.xun@gmail.com">Xun Wang</maintainer>
  <license>BSD</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <build_depend>pyride_common_msgs</build_depend>
  <build_depend>cv_bridge</build_depend>
  <build_depend>image_transport</build_depend>
  <build_depend>rclcpp</build_depend>
  <build_depend>std_msgs</build_depend>

  <exec_depend>pyride_common_msgs</exec_depend>
  <exec_depend>cv_bridge</exec_depend>
  <exec_depend>image_transport</exec_depend>
  <exec_depend>rclcpp</exec_depend>
  <exec_depend>std_msgs</exec_depend>

  <!-- Required for generating interfaces -->
  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>